object Versions {

    const val lifecycleRuntimeVersion = "2.4.0-alpha01"
    const val kotlinVersion = "1.5.31"
    const val coreKtxVersion = "1.6.0"
    const val appCompatVersion = "1.3.1"
    const val materialVersion = "1.5.0-alpha03"
    const val legacySupportVersion = "1.0.0"
    const val jUnitVersion = "4.13.2"
    const val extJUnitVersion = "1.1.3"
    const val espressoVersion = "3.4.0"
    const val coroutinesVersion = "1.4.2"
    const val navigationVersion = "2.3.5"
    const val hiltVersion = "2.37"
    const val fragmentKtxVersion = "1.3.3"
    const val gradleVersion = "7.1.0-alpha02"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "4.9.1"
    const val moshiVersion = "2.9.0"
    const val chuckVersion = "1.1.0"
    const val accompanistVersion = "0.16.0"
    const val javaxInjectionVersion = "1"
    const val glideVersion = "4.12.0"
    const val recyclerViewVersion = "1.2.1"
    const val androidSvgVersion = "1.4"
    const val facebookShimmerVersion = "0.5.0"
    const val mpChartVersion = "v3.1.0"
    const val splashScreenVersion = "1.0.0-alpha02"
}