object Versions {

    const val lifecycleRuntimeVersion = "2.4.0"
    const val kotlinVersion = "1.5.31"
    const val coreKtxVersion = "1.7.0"
    const val appCompatVersion = "1.3.1"
    const val materialVersion = "1.4.0"
    const val legacySupportVersion = "1.0.0"
    const val coroutinesVersion = "1.5.2"
    const val navigationVersion = "2.3.5"
    const val hiltVersion = "2.37"
    const val fragmentKtxVersion = "1.3.6"
    const val gradleVersion = "7.1.0-alpha02"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "4.9.2"
    const val moshiVersion = "2.9.0"
    const val chuckVersion = "1.1.0"
    const val customViewVersion = "1.1.0"
    const val javaxInjectionVersion = "1"
    const val glideVersion = "4.12.0"
    const val recyclerViewVersion = "1.2.1"
    const val androidSvgVersion = "1.4"
    const val facebookShimmerVersion = "0.5.0"
    const val mpChartVersion = "3.1.0"
    const val splashScreenVersion = "1.0.0-alpha02"
    const val mockkVersion = "1.12.0"
    const val truthVersion = "1.1.3"
    const val jUnitKtxVersion = "1.1.3"
    const val robolectricVersion = "4.6.1"
    const val jUnit5Version = "5.8.1"
    const val coroutinesTestVersion = "1.5.2"
    const val archCoreTestingVersion = "2.1.0"

    const val ktLintVersion = "10.2.0"
    const val versionCheckerVersion = "0.39.0"
}