object Versions {

    const val lifecycleRuntime = "2.4.0"
    const val kotlinStdLib = "1.5.31"
    const val coreKtx = "1.7.0"
    const val appCompat = "1.3.1"
    const val material = "1.4.0"
    const val legacySupport = "1.0.0"
    const val coroutines = "1.5.2"
    const val navigation = "2.3.5"
    const val hilt = "2.37"
    const val fragmentKtx = "1.3.6"
    const val retrofit = "2.9.0"
    const val okHttp = "4.9.2"
    const val moshi = "2.9.0"
    const val chuck = "1.1.0"
    const val customView = "1.1.0"
    const val javaxInjection = "1"
    const val ktlint = "0.43.0"
    const val detekt = "1.18.1"
    const val glide = "4.12.0"
    const val recyclerView = "1.2.1"
    const val androidSvg = "1.4"
    const val facebookShimmer = "0.5.0"
    const val mpChart = "3.1.0"
    const val splashScreen = "1.0.0-alpha02"
    const val mockk = "1.12.0"
    const val truth = "1.1.3"
    const val jUnitKtx = "1.1.3"
    const val robolectric = "4.6.1"
    const val jUnit5 = "5.8.1"
    const val coroutinesTest = "1.5.2"
    const val archCoreTesting = "2.1.0"

}